### ISSUE TITLE
Add pitEnabled feature of mongodbatlas_cluster resource

### ISSUE THREAD

**Issue by simon-guerin** [mongodb/terraform-provider-mongodbatlas#104]
I’m trying to automate the deployment of our MongoDB Atlas estate. MongoDB Atlas has an API as part of the cluster configuration which allows to set point in time restore **pitEnabled**

https://docs.atlas.mongodb.com/reference/api/clusters-create-one/

Looking in the documentation for the terraform resource mongodbatlas_cluster it doesn’t have this option

https://www.terraform.io/docs/providers/mongodbatlas/r/cluster.html

Is there a plan to implement this?

**Comment by PacoDw** [comment]
Hello @simon-guerin, thank you so much for your review, let us check because I think it is a new attribute @themantissa.

**Comment by themantissa** [comment]
@PacoDw  and @simon-guerin  yes, that is indeed a newer feature and we'll need to add in support.  We'll want to look to schedule work to support pitEnabled for clusters and some new attributes for both cloud provider snapshot resources.

**Comment by themantissa** [comment]
Just to update this issue pitEnabled will be in the next version due to changes for new AWS clusters no longer supporting continuous backups (e.g. one should now use cloud provider snapshots for new AWS clusters, provider_backup_enabled = true and either unset or not set backup_enabled).  Documentation will also be updated with PR:   https://github.com/terraform-providers/terraform-provider-mongodbatlas/pull/116. Next version expected mid/end Feb, however once pitEnabled is in master we will update so those who require it can test/use before release.
