### ISSUE TITLE
If don't specify IOPS when creating M10 or M20 cluster a 0 value is passed in causing failure

### ISSUE THREAD

**Issue by simon-guerin** [mongodb/terraform-provider-mongodbatlas#120]
Error: error creating MongoDB Cluster: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/123456789abcdefgh/clusters: 400 (request "Bad Request") The cluster's disk IOPS of 0 is invalid. For a disk of size 50 on instance size M10 with a volume type of STANDARD, the IOPS must be 150.0.

This is the error above ^   In the code I don't specify IOPS (the option is completely omitted to allow atlas to define the IOPS) and get this error.   When I run the same code on a M30+ instance it works OK.

I've tested with the MongoDB Atlas API directly and if I create an M10 instance and omit the  IOPS option it spins up the cluster OK.

**Comment by themantissa** [comment]
Hi @simon-guerin  This should have been fixed in the current master branch.  I just tested not specifiying both disk_size_gb and provider_disk_iops for an M10 and it worked so the options are to wait till our next release (mid/late Feb) or build a provider from master and use that till then.  
Thank you!
