### ISSUE TITLE
Online Archive: "Specified cloud provider is not supported in Data Lake Storage" but works in UI

### ISSUE THREAD

**Issue by Heleydin** [mongodb/terraform-provider-mongodbatlas#1216]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/mongodb/mongodbatlas v1.9.0
```

### Steps to Reproduce

Apply the following ressource
```hcl
resource "mongodbatlas_online_archive" "test_archive" {
  project_id   = "my_project_id"
  cluster_name = "my_cluster"
  coll_name    = "my_collection"
  db_name      = "my_db"

  criteria {
    type = "DATE"
    date_field = "my_date"
    expire_after_days = 180
  }

  partition_fields {
    field_name = "_id"
    order = 0
  }
}
```

### Expected Behavior

Ressource created, as it does in the UI.

### Actual Behavior

Error: error creating MongoDB Atlas Online Archive:: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/5e414927d5ec13b97a209188/clusters/malt/onlineArchives: 400 (request "DATA_LAKE_STORAGE_CLOUD_PROVIDER_NOT_SUPPORTED") Specified cloud provider is not supported in Data Lake Storage.

### Additional Context

I think the issue comes from the fact that our cluster is hosted in GCP, and that Online Archive relies on AWS S3 service.
However it works well in the UI, I can create Online Archive without any issues.

**Comment by Zuhairahmed** [comment]
hi @julientard this is a feature request since Specified cloud provider parameter is not yet available on [Online Archive Atlas Admin API resource](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Online-Archive/operation/createOnlineArchive). Can you make this request instead on (or upvote an exisiting one) at https://feedback.mongodb.com/forums/924145-atlas?category_id=389002

Thank you!
