### ISSUE TITLE
Cluster resource's `provider_instance_size_name` should be optional when using autoscaling

### ISSUE THREAD

**Issue by AaronFriel** [mongodb/terraform-provider-mongodbatlas#1299]
When autoscaling is enabled, applying configurations which set the `provider_instance_size_name` field reset the autoscaled instance size to the configured value.

Users would almost certainly prefer that when `auto_scaling_compute_enabled` is true, they do not need to set this value **or** the value is ignored (and the configuration in state is returned on `Read`) so that plans do not update the `cluster` resource.

First reported by a Pulumi user here:
- https://github.com/pulumi/pulumi-mongodbatlas/issues/241

**Comment by colm-quinn** [comment]
Hi @AaronFriel,
For auto-scaling, we currently advise customers to ignore the `instance_size` setting in their Terraform state, see docs at: https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/advanced_cluster#compute_enabled

For an example, see https://github.com/mongodb/terraform-provider-mongodbatlas/issues/1288#issuecomment-1618623996. Can you confirm if the ignore works for you here?

If so, we can look to improving the docs & examples here to make the `ignore_changes` steps clearer/more explicit.

**Comment by AaronFriel** [comment]
@colm-quinn understood, I'm being a bit prescriptive here with regard to "ignore-changes". We at Pulumi see this fairly often with users filing bug reports against providers. This report I filed was the second or third in one day in which the workaround is to use `ignore_changes`. Users often miss this instruction, the provider doesn't behave as expected, and it can be very frustrating.

Rather than rely on `ignore_changes`, a couple tweaks to the provider implementation result in more users falling on the golden path. Either of these work, though the first is preferable as it keeps the output value usable as an input to other resources.

1. Make the field optional, and raise an error when it's required on Create/Update or log a warning when it's set unnecessarily. This puts the user on the right path pretty quickly.
2. Modify the resource methods to ignore this value - essentially always return what's in state.

**Comment by gregoirefra** [comment]
Hi folks, I wanted to add another perspective on this. 

Relying on ignore_changes makes it hard in scenarios where the cluster definition is inside a module. For example, we declare the cluster and other relevant Atlas resources as part of a module that is re-used across more than one environment but not all MongoDB Atlas clusters are expected to be configured with auto-scaling. Because of this, having an `ignore_change` inside the module with the cluster definition would prevent us from re-using it since all declarations of the module would ignore the instance size and be forced to set auto-scaling to `true` with corresponding min and max values. 

Here is an example definition of what I'm mentioning.

Module definition:
```hcl
resource "mongodbatlas_advanced_cluster" "cluster" {
  project_id   = var.project_id
  name         = var.name
  cluster_type = "REPLICASET"
  replication_specs {
    region_configs {
      electable_specs {
        node_count = 3
        instance_size = var.auto_scaling ? null : var.instance_size
      }
      auto_scaling {
        disk_gb_enabled           = true
        compute_enabled           = var.auto_scaling
        compute_min_instance_size = var.auto_scaling ? var.auto_scaling_min : null
        compute_max_instance_size = var.auto_scaling ? var.auto_scaling_max : null
      }
      provider_name = "AWS"
      priority      = 7
      region_name   = "US_EAST_1"
    }
  }
}
}
```

First environment:
```hcl
module "atlas"{
  source = "./atlas"
  project_id = "my_project_id"
  name = "no_autoscaling"
  auto_scaling = false
  instance_size = "M10"
}
```

Second environment:
```hcl 
module "atlas"{
  source = "./atlas"
  project_id = "my_project_id"
  name = "no_autoscaling"
  auto_scaling = true
  auto_scaling_min = "M10"
  auto_scaling_max = "M80"
}
```

So by using `ignore_changes` here, it would become impossible for us to modify the size of the cluster in the first environment.

Also based on the [documentation](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/advanced_cluster#instance_size) this _should_ be supported as the `instance_size` is marked as optional but it doesn't seem to be the case. I've opened a [separate issue](https://github.com/mongodb/terraform-provider-mongodbatlas/issues/1311) for this.

**Comment by Zuhairahmed** [comment]
Hi just as an update this item is on our roadmap, but still several quarters away. internal tracking ticket [CLOUDP-215040](https://jira.mongodb.org/browse/CLOUDP-215040)

**Comment by OlehHarmash** [comment]
> Hi just as an update this item is on our roadmap, but still several quarters away. internal tracking ticket [CLOUDP-215040](https://jira.mongodb.org/browse/CLOUDP-215040)

Hello

Our team is also interested in that feature.
Do you have any updates?

**Comment by Zuhairahmed** [comment]
hi given this ticket has been outstanding for a long time, resolving as we will not do. best way to clean up would be to introduce a fix through the Atlas Admin API, not through our Terraform Provider. feel free to reach out if you need anything else and thank you for understanding.
