### ISSUE TITLE
Inconsistent documentation between GitHub repo and Terraform site

### ISSUE THREAD

**Issue by MontgomeryWatts** [mongodb/terraform-provider-mongodbatlas#136]
When trying to whitelist an AWS security group in a `mongodbatlas_project_ip_whitelist` resource it says `An argument named "aws_security_group" is not expected here.` After looking through the repository it seems like this should be a valid argument.

My `mongodbatlas_project_ip_whitelist` resource looks like this:

```
resource "mongodbatlas_project_ip_whitelist" "mongodb_whitelist" {
 project_id = "${mongodbatlas_project.mongodb_atlas_playlist_project.id}"
 aws_security_group = "${aws_security_group.mongodb_lambda_security_group.id}"
}
```

After looking at the docs [in this repo ](https://github.com/terraform-providers/terraform-provider-mongodbatlas/blob/master/website/docs/r/project_ip_whitelist.html.markdown#argument-reference) I compared them to the docs on the [Terraform site](https://www.terraform.io/docs/providers/mongodbatlas/r/project_ip_whitelist.html). Each version shows two different things for this resource, do you know why this might be?

**Comment by themantissa** [comment]
@MontgomeryWatts that's because what is in the repo is a master branch and may contain code and documentation not yet released.  You are likely using version 0.3.1 and that does not contain support for aws security groups yet.  We hope to release 0.4.0 today, which will (I'll post a notice in the issues section of this repo).   You an always see what is included in the current version released by checking the CHANGELOG file.
