### ISSUE TITLE
Information - Upgrade Guide for 0.4.0 - Especially for Project IP Whitelist 

### ISSUE THREAD

**Issue by themantissa** [mongodb/terraform-provider-mongodbatlas#139]
This is our guide for upgrading to 0.4.0 as it contains a major change to address  [issues](https://github.com/terraform-providers/terraform-provider-mongodbatlas/issues/51) brought up here in regard to the first version of Project IP Whitelist support.   0.4.0 greatly improves the experience of Project IP Whitelist management but does take some effort to implement.   Please read the guide before upgrading: 
[https://www.mongodb.com/blog/post/upgrade-guide-for-terraform-mongodb-atlas-040](https://www.mongodb.com/blog/post/upgrade-guide-for-terraform-mongodb-atlas-040)
and 
[https://www.mongodb.com/blog/post/new-major-version-of-terraform-mongodb-atlas-provider](https://www.mongodb.com/blog/post/new-major-version-of-terraform-mongodb-atlas-provider)

This new version also includes the ability to add AWS Security Groups to the whitelist, as well as much more.

**Comment by simond-b2** [comment]
Hi, we are currently fixed on version 0.3.0 as we are having an issue with the whitelist entries in 0.4.0.  I believe the white list entries that we specify are in agreement with your upgrade guide and associated documentation.

Terraform version 0.12.20
mongodbatlas provider version 0.4.0

So trying to deploy to an Azure environment we attempt to create a mongo atlas cluster via terraform, but get the following error:

**Error: error getting Project IP Whitelist information: whiteListEntry is invalid because must be set**

The following entry validates ok (ip address redacted), but generates the above error at run time :

resource “mongodbatlas_project_ip_whitelist” “test” {
project_id = mongodbatlas_project.test[0].id

cidr_block = “1.2.3.4/32”
comment = “Test whitelist (terraform managed)”
}

**Comment by themantissa** [comment]
@simond-b2 I just tested creating a multi-region Azure cluster with multiple IP Whitelist entries and no issues.   Are you perhaps setting up or have setup network peering as well?   Also are you sure you are using the more recent provider (check with terraform --version).   If you continue to have issues I would suggest working with Atlas support as I'll be out of pocket for a few days.

**Comment by simond-b2** [comment]
@themantissa Thanks for the feedback, I have checked and we have no network peering setup and the versions are those I gave previously ...
**Terraform version 0.12.20
mongodbatlas provider version 0.4.0**
I will work with Atlas as you suggest but could I ask one further thing before you leave our pockets ... the cluster is already deployed.  Would this prevent the whitelists deploying correctly? I.e. did you set up a completely clean Atlas deployment?

Thanks again

**Comment by rwenz3l** [comment]
Hey @simond-b2 - encountered the same issue today after upgrading to the new provider version.

It is indeed correct, that this new approach works, if you are setting up a new ("clean") cluster. For everyone else who already maintains the state within terraform, you need to remove them and re-import with their "whiteListEntry". The "whiteListEntry" is basically the CIDR Range or IP Address. It's not well documented, really (I blame MongoDB here, not the terraform folks).

Example:

We have a fake project id = `dc260d4639e1abf8b8aa1f94` (=> `openssl rand -hex 12`)
And we have the common "Allow from Anywhere" rule in your project:
![image](https://user-images.githubusercontent.com/7768249/75444175-3ee43900-5963-11ea-9568-b1d0f4c01da5.png)

And it is already defined in terraform:

```hcl
resource "mongodbatlas_project_ip_whitelist" "anywhere" {
  project_id = "dc260d4639e1abf8b8aa1f94"
  cidr_block = "0.0.0.0/0"
  comment = "Allow from anywhere."
}
```

So to make this existing rule work:

```sh
# remove it from your state
terraform state rm mongodbatlas_project_ip_whitelist.anywhere

# and re-import it like this:
terraform import \
mongodbatlas_project_ip_whitelist.anywhere \
dc260d4639e1abf8b8aa1f94-0.0.0.0/0

# where the pattern is:
terraform import \
mongodbatlas_project_ip_whitelist.<your_entry_name_in terraform> \
<project_id>-<cidr_range|ip_address>
```

Hope that helps.

Also @themantissa - maybe the docs need to be updated or this qualifies as a bug, because I expect terraform to pickup the existing resource. It actually told me when I tried to import it:

```
 terraform import mongodbatlas_project_ip_whitelist.anywhere dc260d4639e1abf8b8aa1f94-0.0.0.0/0
mongodbatlas_project_ip_whitelist.anywhere: Importing from ID "dc260d4639e1abf8b8aa1f94-0.0.0.0/0"...
mongodbatlas_project_ip_whitelist.anywhere: Import prepared!
  Prepared mongodbatlas_project_ip_whitelist for import

Error: Resource already managed by Terraform

Terraform is already managing a remote object for
mongodbatlas_project_ip_whitelist.anywhere. To import to this address you must
first remove the existing object from the state.
```

Edit:
Source where I found this: https://github.com/terraform-providers/terraform-provider-mongodbatlas/blob/master/website/docs/r/project_ip_whitelist.html.markdown#import

Also now that I'm linking this, the import statement is wrong, according to the message I got it should use the `<project_id>-<whiteListEntry>`.

**Comment by simond-b2** [comment]
@rwenz3l Thanks for looking and for the work-around, I've had to skip on to higher priority issues at the moment but will revisit this later as we are ok on 0.3.0 for the time being.  @themantissa should we raise this as a bug or continue to implement Robin's workaround?

Thanks both I appreciate you taking the time to investigate.

**Comment by themantissa** [comment]
The workaround cited is within the upgrade guide https://www.mongodb.com/blog/post/upgrade-guide-for-terraform-mongodb-atlas-040
We had to do a breaking change to create a better experience for IP Whitelists due to the way the Atlas API works within the system and that is documented within the guide - including that one needs to remove the existing from state and reimport.

**Comment by themantissa** [comment]
Since 0.4.0 is long since a supported version we are closing this issue. The guides like this are now available in the Terraform registry: https://registry.terraform.io/providers/mongodb/mongodbatlas/latest
