### ISSUE TITLE
Add name argument in mongodbatlas_project datasource

### ISSUE THREAD

**Issue by aklotos** [mongodb/terraform-provider-mongodbatlas#140]
As previously pointed at in [this issue](https://github.com/terraform-providers/terraform-provider-mongodbatlas/issues/137) there is a convenience in retrieving of `mongodbatlas_project` by `name` as well. It used to be available in `v0.3.0` and not available anymore. Currently `mongodbatlas_project` datasource accepts only `project_id` as an argument as per [documentation](https://www.terraform.io/docs/providers/mongodbatlas/d/project.html#argument-reference).

Moreover a side question. I consider this change in datasource argument a breaking change. Is it expected that with a breaking change only minor version of tf provider is changed?

**Comment by marinsalinas** [comment]
Hello, @aklotos name was changed to project id on this commit https://github.com/terraform-providers/terraform-provider-mongodbatlas/commit/a9ae7aa89c58047c058e4d74b3e60b89a2a10725#diff-6fa79410e48e7733c5f9838df2fb07ba

@PacoDw what was the reason for this change?

**Comment by PacoDw** [comment]
Hello @aklotos and @marinsalinas,
 I'm so sorry for all the things it causes, I changed it to improve the project data source, and to have coherency with the other resources, handle the resource with an ID is better.

**Comment by themantissa** [comment]
@PacoDw  and @marinsalinas thank you for the quick investigation in the matter.

@aklotos this was indeed a regression and will be corrected.   Appreciate that you filed an issue.

Regarding the side question - while this change was not intentional if we must make a breaking change we will include it in an upgrade-guide (see issue [139](https://github.com/terraform-providers/terraform-provider-mongodbatlas/issues/139) for the last example.  We've been staying in a minor version pattern until we are close to covering the majority of Atlas' functionality, at that point it will make sense to be at 1.0.0 (other providers followed a similar pattern from my own investigations).  Each version jump we've done quite a bit, as covered in the CHANGELOG so they may be minor but building quite a bit each time.   I hope that helps clarify but always feel free to reach out and ask if you have any concerns.

**Comment by themantissa** [comment]
Final note: we'll release a minor version early next week with this fix.
