### ISSUE TITLE
Breaking change to drop deprecated fields made in minor version release

### ISSUE THREAD

**Issue by benjamin-pilgrim** [mongodb/terraform-provider-mongodbatlas#1493]
PR #1418, which was tagged with `breaking-change` was released in a minor version bump, breaking backwards compatibility.

As a result, our terraform runs are failing with:

```
│ Error: Unsupported attribute
│ This object does not have an attribute named "aws_private_link_srv".
```

**Comment by Zuhairahmed** [comment]
hi @TGNThump, we apologize for the friction that this has caused you and your team. as of late, our versioning scheme has become an increasing focus for us internally and we may have changes to our approach in the near future to provide our users more visibility, clarity, and consistency with other terraform providers. 

with that said, we currently follow a non-standard semantic versioning approach where instead of MAJOR.MINOR.PATCH, we use a 0.Major.Minor approach. so for us, v1.12.0 release we considered a major release with potential to have breaking changes (though we do try to limit breaking changes as much as possible) and our latest version v1.12.1 would be considered a minor release which we are guaranteeing not to have any breaking changes. 

we plan to release documentation and additional guidance here as mentioned once we have aligned on best long term approach for our users. in the interim, would love to hear your feedback @TGNThump in case you have anything else to share? again appreciate your patience and understanding here until we get there.

**Comment by Zuhairahmed** [comment]
Resolving issue, if there is anything else you need feel free to create a new issue. Thank you.
