### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by mpsanten** [mongodb/terraform-provider-mongodbatlas#1708]
We bumped our provider version for this module from 1.9.0 to 1.13.1.  Now we get an error:

╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.message_history_service_project.module.project.mongodbatlas_project.project,
│ provider "provider[\"registry.terraform.io/mongodb/mongodbatlas\"]"
│ produced an unexpected new value: .teams: planned set element
│ cty.ObjectVal(map[string]cty.Value{"role_names":cty.SetVal([]cty.Value{cty.StringVal("GROUP_DATA_ACCESS_ADMIN")}),
│ "team_id":cty.StringVal("6[27](https://github.com/RoyalAholdDelhaize/sre-infra-mongodb/actions/runs/7099166189/job/19323118982#step:9:28)a70e10bd68f7ed5142c70")}) does not correlate
│ with any element in actual.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Error: Process completed with exit code 1.

**Comment by marcosuma** [comment]
Hi @mpsanten, thank you for raising your issue to us. In order to provide support, we kindly ask you to [follow our guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/issues/new?assignees=&labels=&projects=&template=Bug_Report.md) and fill up all the required info that are asked when creating an issue.

Without that information, we won't be able to provide support. Thank you again for your patience.

**Comment by mpsanten** [comment]
1) included as terraform.tf in attached 1708.zip
2) included as logs.txt in attached 1708.zip
3) provider version used 1.13.1   I experienced the same error in version 1.13.0 but when I downgrade to 1.9.0, I have no issue
4) Terraform version 1.6.5
5) Terraform OSS

[1708.zip](https://github.com/mongodb/terraform-provider-mongodbatlas/files/13562279/1708.zip)

**Comment by marcosuma** [comment]
Thank you @mpsanten, we will have a look internally with the team and provide and answer as soon as possible.

**Comment by marcosuma** [comment]
Hi @mpsanten, unfortunately I wasn't able to reproduce the issue. This is the script I used:

```
terraform {
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "1.13.0"
    }
  }
  required_version = "= 1.6.5"
}

provider "mongodbatlas" {
  private_key = var.private_key
  public_key  = var.public_key
}

variable "private_key" {
  type = string
  default = "<VALUE>"
}

variable "public_key" {
  type = string
  default  = "<VALUE>"
}

variable "org_id" {
  type = string
  default = "ORG_ID"
}

variable "member_teams" {
  type = list
  default = ["team_1", "team_2"]
}


data "mongodbatlas_teams" "members" {
  for_each = toset(var.member_teams)

  org_id = var.org_id
  name   = each.value
}



resource "mongodbatlas_project" "project" {
  name   = "project_test"
  org_id = var.org_id

  with_default_alerts_settings = false // Else it sets up a lot of email alerts, use basic-alertset moodule for default alert settings we create with OpsGenie integration.

  dynamic "teams" {
    for_each = data.mongodbatlas_teams.members

    content {
      team_id    = teams.value["team_id"]
      role_names = ["GROUP_DATA_ACCESS_ADMIN"] // Groups and projects are synonymous terms. You may find group_id in the official documentation.
    }
  }
}
```

I wasn't able to use the module used in your script. 
Can I suggest you to try to replicate the issue on your side **without** using the module but just using static values? This should help understand where the problem is.

**Comment by marcosuma** [comment]
Marking as stale again, it will auto-close in 7 days if no update.
