### ISSUE TITLE
connection_strings returning empty private values

### ISSUE THREAD

**Issue by mpaluchowski** [mongodb/terraform-provider-mongodbatlas#220]
I'm trying to access the `connection_strings.private` value from our cluster, but I'm getting an empty string there:

```
mongodbatlas_cluster.default.connection_strings[0].private is ""
```

The cluster:

* exists and is functional,
* does have an AWS VPC Peering setup,
* the regular address for it (with the new `.` dot for universal addresses -- the one returned from `connection_strings.standard`) resolves correctly to a private IP when called from within our VPC.

It seems we have all the pieces in place, but still, the value is empty.

**Comment by PacoDw** [comment]
Hello @mpaluchowski the private values take more time to get done, it's necessary to make `terraform refresh` to see the values in your terraform state. Also, you can confirm them on your MongoDB console to verify when they are done in order to make `terraform refresh`. This happens due to the terraform flow, we can't wait for the peering connection resource to be done because we need the cluster first, for this reason, we can't track that resource.

Let me know if you have another comment or concern, thanks

**Comment by mpaluchowski** [comment]
Thank you for explaining this.

Could you update the [documentation for `mongodbatlas_cluster`](https://www.terraform.io/docs/providers/mongodbatlas/r/cluster.html) to include these instructions for running `terraform refresh`?

And how about running `data "mongodbatlas_cluster"` to get the `connection_strings.private`? Would that include the strings once the cluster is up and running? If so, documentation could also be update to advise on using `data` here.
