### ISSUE TITLE
Use SemVer Appropriately

### ISSUE THREAD

**Issue by KrisJohnstone** [mongodb/terraform-provider-mongodbatlas#2656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

Any

### Terraform Version

Any

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

When ever a breaking change occurs the minor version is updated rather then the major version. If your making a breaking change, it shouldn't be a minor patch.

Link to [semver](https://semver.org/)

### Terraform configuration to reproduce the issue

```hcl
N/A
```

### Steps To Reproduce

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maastha** [comment]
Hi @KrisJohnstone, 
We apologize for the friction that this has caused you and your team. Our versioning scheme has become an increasing focus for us internally and we may have changes to our approach in the near future to provide our users more visibility, clarity, and consistency with other terraform providers.

That said, we currently follow a non-standard semantic versioning approach where instead of MAJOR.MINOR.PATCH, we use a 0.Major.Minor approach. So for us, v1.20.0 release, for example, was considered a major release with potential to have breaking changes (though we do try to limit breaking changes as much as possible) and a version v1.20.1 would be considered a minor release which we are guaranteeing not to have any breaking changes.

We plan to release documentation and additional guidance here as mentioned once we have aligned on best long term approach for our users. In the interim, would love to hear your feedback @KrisJohnstone in case you have anything else to share? again appreciate your patience and understanding here until we get there.

**Comment by Zuhairahmed** [comment]
hi @KrisJohnstone are you available for a quick call? feel free to email me directly and happy to find the time zuhair.ahmed@mongodb.com. we appreciate your feedback and happy to chat more about this topic

**Comment by KrisJohnstone** [comment]
Apologies if it was a little abrupt. I just couldn't think of anything more that added alot of value. Allow me to expand on why I raised the issue.

Its nice when software standardizes on what major.minor.patch is and what it means, there's so much context that we all need to remember about various products and tools that it would be nice to not have to also remember the differences in versioning between all the different products we use.

Further using a standardised versioning system allows folks to automate dependency management with rules allowing minor versions to be merged, but not major versions. Tooling doesn't typically allow for all minor version prs but mongo prs to auto merge for example.

EDIT: I do like that each release is clearly labeled with whats breaking.
