### ISSUE TITLE
There is no parity between the Atlas API documentation and the provider doc in regards to alert event_type values

### ISSUE THREAD

**Issue by dryabtse** [mongodb/terraform-provider-mongodbatlas#295]
[Alert configuration](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/alert_configuration) lists a limited number of `event_type` values if compared to the values [documented for Atlas API](https://docs.atlas.mongodb.com/reference/api/events/).

**Comment by themantissa** [comment]
@dryabtse  the API resource https://docs.atlas.mongodb.com/reference/api/events/ is slightly different than alerts, events is the resource to obtain activity feed data (e.g. https://docs.atlas.mongodb.com/tutorial/activity-feed/index.html) and https://docs.atlas.mongodb.com/reference/api/alerts/ (related https://docs.atlas.mongodb.com/alerts/) is what maps as the consumption side of the alert configurations.  Hence there is no parity because they are slightly different areas.

Also related the API documentation for https://docs.atlas.mongodb.com/reference/api/alert-configurations/ was recently updated w/ our internal teams (completed) and we will soon improve the provider to better support what is configurable/not and better reflect that in the Terraform documentation.  (see #232 and #237).

**Comment by dryabtse** [comment]
Hi @themantissa . From your comment it's not clear if it will be possible to deploy exactly the same alert configuration via tf provider as it if the Atlas API was used natively. This is what I meant by "parity". If the provider is unable to deploy certain alert types, then that is most certainly a defect IMO and should be treated as such.

**Comment by themantissa** [comment]
@dryabtse in my comment I was trying to clear up the different between the areas linked to in your issue as they are not the same thing (events is different than alerts).

But yes, we are working in the aforementioned PRs to allow the provider to have what parity, to use the terminology, w/ that the documentation has currently.
