### ISSUE TITLE
mongodbatals_network_container

### ISSUE THREAD

**Issue by RavindraSinghKhichi** [mongodb/terraform-provider-mongodbatlas#336]
I have noticed that all of the Terraform resources or APIs are accepting region values as a-b-1 
Ex: us-west-1 

but here https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/data-sources/network_container, this resource expects value as us_west_1, this syntax right there a_b_1 is breaking the pattern and somehow making it difficult for us to keep two syntaxes. 

Is this intended?

**Comment by nikhil-mongo** [comment]
@RavindraSinghKhichi Yes this is intended because as per the Atlas API, the syntax a_b_1 as mentioned in this [documentation](https://docs.atlas.mongodb.com/reference/amazon-aws/#amazon-aws) is used for all Atlas related API parameters.

However, AWS refers them as a-b-1, so wherever we have to define anything specifics related to AWS and which is not under our API, such as VPC peering, we use the syntax as defined by AWS.

Therefore, yes these two types of syntaxes will have to be used.

**Comment by themantissa** [comment]
@RavindraSinghKhichi looks like @nikhil-mongo answered your question so closing this issue. Thank you!
