### ISSUE TITLE
Tenant Provider Acceptance tests are failing

### ISSUE THREAD

**Issue by Freyert** [mongodb/terraform-provider-mongodbatlas#419]
Just wanted to point out that your acceptance tests have been failing for some time now.

Looks like all tests using the `TENANT` provider fail because they want MongoDB version 4.2, but get 4.4.4.

```
TestAccResourceMongoDBAtlasCluster_tenant_m5
mongo_db_major_version:  "4.4" => "4.2"
mongo_db_version: "4.4.4" => "4.4.4"

TestAccResourceMongoDBAtlasCluster_tenant
mongo_db_major_version:  "4.4" => "4.2"
mongo_db_version: "4.4.4" => "4.4.4"
```

[testAccMongoDBAtlasClusterConfigTenant](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/fea51f6c70d96f65912af43cfc5686dafbecaf88/mongodbatlas/resource_mongodbatlas_cluster_test.go#L1150) specifies `mongo_db_major_version = "4.2"` for both tests.

[testAccMongoDBAtlasClusterConfigTenantUpdated](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/fea51f6c70d96f65912af43cfc5686dafbecaf88/mongodbatlas/resource_mongodbatlas_cluster_test.go#L1170) updates the config to not include specifying the `mongo_db_major_version` which I assume causes a fallback to a default during `TestAccResourceMongoDBAtlasCluster_tenant`.

I notice there are also a wide variety of tests specifying several different versions of MongoDB, but no clear reason for choosing any version. May be a good time to parameterize that and make the version common.

Do you have plans to fix these tests? Is there a known reason why they are failing? I couldn't find a related issue.

### References
* [INTMDB-185 Acceptance Tests Run](https://github.com/mongodb/terraform-provider-mongodbatlas/runs/2071482038)

**Comment by themantissa** [comment]
@Freyert thank you for the note. We look into and triage test failures in a prioritized order.  Recently the default for TENANT, aka shared, tier clusters moved to 4.4 but we have not yet updated the tests to reflect that but will (this is tracked in our internal ticketing system so most of these situations have no issue filed).  

In regard to why multiple versions, that's mostly due to the fact that our dedicated clusters allow users to specify specific versions of MongoDB depending on what is supported while Tenant/shared always default to a specific version. Hence we use a range to ensure we cover the range of potential users.   It may have sense to parameterize at some point but right now it's not a prioritized item.  

Thanks!
