### ISSUE TITLE
Multi cloud not supported?

### ISSUE THREAD

**Issue by RishithRavi** [mongodb/terraform-provider-mongodbatlas#497]
I am trying to implement mongodb atlas multi cloud in terraform and I am not able to see any mention of multi cloud in the documentation.

Please see the link below for additional information about mongodb atlas multi cloud setup.

https://docs.atlas.mongodb.com/cluster-config/multi-cloud-distribution/

**Comment by themantissa** [comment]
@RishithRavi  Multi-cloud is not yet supported in Terraform.  It is on the near term roadmap.

**Comment by RishithRavi** [comment]
Thanks for the quick response

**Comment by 1uk4sh** [comment]
Hi @themantissa ,
thanks for implementing this feature!

I'm a little confused when this feature was exactly released. I can find this Issue is listed as closed in the `v1.0.0-pre.1` changelog, but #570 is only included in the `v1.1.0` changelog.
Can the changelog be fixed?

Any chance to have the term `multi-cloud` included in the changelog as a feature (similar to the docs #609 )?

Thanks
