### ISSUE TITLE
mongodbatlas_network_containers datasource doesn't work with Azure

### ISSUE THREAD

**Issue by ansi4** [mongodb/terraform-provider-mongodbatlas#71]
The _mongodbatlas_network_containers_ data source doesn't work with providers other than AWS.

This happens because you cannot specify providerName for this data source in terraform and, if absent, it defaults to AWS, as specified in the [documentation](https://docs.atlas.mongodb.com/reference/api/vpc-get-containers-list/). It results in empty list of containers for Azure.

**Comment by themantissa** [comment]
Hi @ansi4 can you provide more information around the specific problem you hit when trying to create with Azure, your .tf/errors, etc?  We've tested creating peering with all 3 supported cloud providers and all three passed so want to be sure we are focused on any issue you've had.  Also note you need the resource https://www.terraform.io/docs/providers/mongodbatlas/r/private_ip_mode.html w/ Azure and GCP as well.   Finally, since support is provided directly via Atlas support have you worked w/ them yet so I can check on any support tickets?

**Comment by ansi4** [comment]
Hi @themantissa. Thank you for looking into it.

Basically there is no issue creating the peering. The issue manifests itself when you try to retrieve peering containers using [_data.mongodbatlas_network_containers_](https://www.terraform.io/docs/providers/mongodbatlas/d/network_containers.html). It yields no results, despite the fact that the container is present (I've checked by calling API).

It is not an Atlas issue either, since they write in the [documentation](https://docs.atlas.mongodb.com/reference/api/vpc-get-containers-list/): 
> If you do not specify the cloud provider, Atlas defaults to Amazon Web Services (AWS).

So, to use anything other than that you have to specify it. But, since [network_containers](https://www.terraform.io/docs/providers/mongodbatlas/d/network_containers.html) won't let you specify providerName - it defaults to AWS and returns empty list.

**Comment by themantissa** [comment]
@ansi4 ah, that helps quite a bit. We had a fix go in for a similar issue for the resource so perhaps just needs to be addressed for containers as well.  Will ask the team to look into this.  Thank you!
