### ISSUE TITLE
MongoDB Atlas Auditing needs to be recreated if project is recreated (Add ForceNew to project_id)

### ISSUE THREAD

**Issue by marinsalinas** [mongodb/terraform-provider-mongodbatlas#759]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
# Copy-paste your version info here
terraform provider --version
Terraform v1.0.6
on darwin_amd64
+ provider registry.terraform.io/mongodb/mongodbatlas v1.3.0
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_project" "this" {
  name             = var.project_name
  org_id           = var.organization_id
  project_owner_id = var.project_owner_user
}

#Add Datadog integration
resource "mongodbatlas_third_party_integration" "datadog" {
  count      = var.datadog_api_key != "" ? 1 : 0
  project_id = mongodbatlas_project.this.id
  type       = "DATADOG"
  api_key    = var.datadog_api_key
  region     = "US"
}


resource "mongodbatlas_auditing" "this" {
  project_id                  = mongodbatlas_project.this.id
  audit_filter                = var.audit_filter
  audit_authorization_success = false
  enabled                     = var.auditing_enabled
}

```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. Modify Project name
4. `terraform plan`
5. `terraform apply`

### Expected Behavior

Audit Filter should be recreated to reflect new's project id

### Actual Behavior

```bash
Error: error updating MongoDB Auditing (62b4c982a06c3d7c291771db): PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/62b4c982a06c3d7c291771db/auditLog: 404 (request "GROUP_NOT_FOUND") No group with ID 62b4c982a06c3d7c291771db exists.
with module.dbtfmodules_project.mongodbatlas_auditing.this
on ../modules/project-config/main.tf line 32, in resource "mongodbatlas_auditing" "this":
resource "mongodbatlas_auditing" "this" {
````

**Comment by themantissa** [comment]
@marinsalinas how fun to get an issue from one of our former developers! :)   Hope you are well.   This brings up an interesting point about resources that are created for a project.  Since they are linked to the project the assumption we've had thus far and have seen in customer examples is that when one deletes the project it's created for they will delete the auditing resource as well, since it is not needed when the project is deleted. When a new project is created it should be created with a new auditing resource as well for that project.   Is there a specific reason you want to keep auditing the resource block same but basically move it to a new project, as opposed to the above workflow?

**Comment by marinsalinas** [comment]
We develop Terraform modules, so I ran into this issue when a user tried to rename a project (which causes project recreation), so basically we are using the exact same resources blocks, so the auditing resource wants to be updated instead of recreated when a new project id is set.

**Comment by themantissa** [comment]
@marinsalinas apologies for the delay.   Since this is a bit of an edge case we haven't had chance to address yet. I created a ticket in our backlog to review as we do want to be careful with any ForceNew unless we are sure of the impact.  I think in this case it may make sense.  The internal ticket is INTMDB-435.  I'm going to close this issue for now but we can updated if we get it address.  If it becomes a bigger issue for you Marin please let us know via a new issue.   cc @Zuhairahmed
